# Site settings
title: AL林
description: Algorithm Problem Solving Study
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: AL林
user_description: AL林[알-림]은 서울시립대학교 컴퓨터과학부 소속 알고리즘 문제 해결 소모임입니다. 저희는 다음과 같은 활동을 합니다.
user_title: Algorithm Problem Solving Study
email: miriv.sh@gmail.com
twitter_username: 
github_username:  all1m-algorithm-study
gplus_username:  miriv.sh

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
